# caso adicione um link externo, este deve começar com http, ou seja, a url completa

- label: Cursos
  route: https://cursos.unirobotica.com.br

- label: Informática Aplicada
  route: /informatica-aplicada

- label: Python Básico
  route: https://python.unirobotica.com.br

- label: About
  route: /about

